name: project
description: Parse the dart project and convert it into a dart node, so that some command-line tools can quickly parse the project.
version: 0.1.1
homepage: https://github.com/CaiJingLong/dart_project

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  yaml: ^2.0.0
  path: ^1.7.0
  pub_semver: ^1.4.0
  analyzer: ^0.40.0
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
