name: project
description: Parse the dart project and convert it into a dart node, so that some command-line tools can quickly parse the project.
version: 0.2.0
homepage: https://github.com/CaiJingLong/dart_project

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  path: ^1.8.1
  pub_semver: ^2.1.1
  analyzer: ^3.4.1
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
